CREATE TABLE project
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(100),
    description VARCHAR(255),
    status      VARCHAR(255)                            NOT NULL,
    start_date  date,
    end_date    date,
    CONSTRAINT pk_project PRIMARY KEY (id)
);