CREATE TABLE task
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(150)                            NOT NULL,
    description VARCHAR(255),
    status      VARCHAR(255)                            NOT NULL,
    priority    VARCHAR(255)                            NOT NULL,
    due_date    date                                    NOT NULL,
    project_id  BIGINT,
    CONSTRAINT pk_task PRIMARY KEY (id)
);

ALTER TABLE task
    ADD CONSTRAINT FK_TASK_ON_PROJECT FOREIGN KEY (project_id) REFERENCES project (id);